"use client"

import * as React from "react"
import Link from "next/link"
import { motion } from "framer-motion"
import { Button } from "@/components/ui/Button"
import { LogoMarquee } from "@/components/marketing/LogoMarquee"
import { ProductDashboard } from "@/components/marketing/ProductDashboard"
import { TestimonialCard } from "@/components/ui/TestimonialCard"
import { Accordion } from "@/components/ui/Accordion"
import { cn } from "@/lib/utils"

const FAQS = [
  {
    title: "What is Growcin?",
    content:
      "Growcin is an AI marketing platform that helps businesses automate SEO, social media, ads, email, analytics, and lead management from a single workspace — so growth compounds without adding headcount.",
  },
  {
    title: "Is there a free trial?",
    content:
      "Yes. Every plan starts with a 14-day free trial. No credit card required. You can explore the dashboard, AI content tools, and campaign intelligence before you commit.",
  },
  {
    title: "Who is Growcin built for?",
    content:
      "Founders, marketing teams, and agencies that want predictable growth without babysitting every channel. If you run ads, content, or outbound and need one system that ties it together, Growcin is for you.",
  },
  {
    title: "How is Growcin different from ChatGPT or Ads Manager?",
    content:
      "ChatGPT writes copy. Ads Manager runs spend. Growcin connects both — generating content, monitoring campaign health, qualifying leads, and recommending the next action with context across your marketing stack.",
  },
  {
    title: "Can I book a demo instead of starting a trial?",
    content:
      "Absolutely. Use Book a Demo to walk through the product with our team. We'll show the dashboard, AI workflows, and how Growcin maps to your current channels.",
  },
  {
    title: "Is Growcin related to Devora?",
    content:
      "Yes. Growcin is the flagship SaaS product built by Devora Tech Studio — designed with the same premium engineering and product craft as Devora's client work.",
  },
]

const FEATURES = [
  {
    icon: "search",
    badge: "SEO",
    title: "AI SEO Strategy",
    desc: "Keyword opportunities, on-page recommendations, and content briefs generated by AI.",
    bullet: "Ranks higher on Google",
  },
  {
    icon: "edit_note",
    badge: "Content",
    title: "AI Blog Writer",
    desc: "Long-form posts tuned to your brand voice and ready to publish in minutes.",
    bullet: "10x writing speed",
  },
  {
    icon: "share",
    badge: "Social",
    title: "AI Social Posts",
    desc: "Platform-native drafts for LinkedIn, Instagram, and X scheduled from one calendar.",
    bullet: "Auto-scheduling",
  },
  {
    icon: "ads_click",
    badge: "Ads",
    title: "AI Ads & Safety",
    desc: "Creative variants, audience signals, and cost safety guardrails so spend stays efficient.",
    bullet: "Zero budget waste",
  },
  {
    icon: "mail",
    badge: "Email",
    title: "AI Email Marketing",
    desc: "Sequences, subject lines, and send-time optimization that convert leads into sales.",
    bullet: "Higher open rates",
  },
  {
    icon: "insights",
    badge: "Analytics",
    title: "AI Analytics",
    desc: "Cross-channel performance in plain language — what moved, why it matters, what to do next.",
    bullet: "Plain-English reports",
  },
  {
    icon: "hub",
    badge: "Leads",
    title: "AI CRM & Leads",
    desc: "Qualify inbound leads automatically and route high-intent conversations to sales.",
    bullet: "Instant lead scoring",
  },
  {
    icon: "bolt",
    badge: "Automation",
    title: "Marketing Automation",
    desc: "Connect campaigns, content, and follow-ups into workflows that run 24/7.",
    bullet: "Runs 24/7 automatically",
  },
]

const WORKFLOW = [
  {
    step: "01",
    title: "Connect your channels",
    desc: "Link ads, analytics, social, and CRM in minutes. Growcin maps your existing stack — no rip-and-replace.",
  },
  {
    step: "02",
    title: "Let AI build & monitor",
    desc: "Generate content, launch campaigns, and watch CPA, fatigue, and lead quality in real time.",
  },
  {
    step: "03",
    title: "Act on clear next moves",
    desc: "Every alert comes with cause and recommendation — so your team decides faster and wastes less budget.",
  },
]

const INTEGRATIONS = [
  { name: "Meta Ads", icon: "campaign" },
  { name: "Google Ads", icon: "ads_click" },
  { name: "Google Analytics", icon: "analytics" },
  { name: "HubSpot", icon: "hub" },
  { name: "Salesforce", icon: "database" },
  { name: "Mailchimp", icon: "mail" },
  { name: "WhatsApp", icon: "chat" },
  { name: "Slack", icon: "forum" },
  { name: "LinkedIn", icon: "work" },
  { name: "Shopify", icon: "storefront" },
  { name: "WordPress", icon: "language" },
  { name: "Zapier", icon: "electrical_services" },
]

const STATS = [
  { value: "2,400+", label: "Businesses growing with Growcin" },
  { value: "$18M+", label: "Ad spend monitored monthly" },
  { value: "4.8/5", label: "Average customer rating" },
  { value: "14 days", label: "Free trial · no card needed" },
]

export default function Home() {
  const [dashView, setDashView] = React.useState<"dashboard" | "analytics" | "writer" | "campaigns">(
    "dashboard"
  )
  const [isAnnual, setIsAnnual] = React.useState(true)
  const [demoPlaying, setDemoPlaying] = React.useState(false)

  React.useEffect(() => {
    const views: Array<"dashboard" | "analytics" | "writer" | "campaigns"> = [
      "dashboard",
      "analytics",
      "writer",
      "campaigns",
    ]
    const id = setInterval(() => {
      setDashView((prev) => {
        const idx = views.indexOf(prev)
        return views[(idx + 1) % views.length]
      })
    }, 4500)
    return () => clearInterval(id)
  }, [])

  return (
    <div className="flex flex-col w-full overflow-hidden">
      {/* Hero */}
      <section className="relative hero-atmosphere pt-24 sm:pt-28 md:pt-32 pb-8 md:pb-12 px-4 sm:px-6 overflow-hidden">
        <div className="absolute inset-0 hero-grid-pattern pointer-events-none" />
        <div className="absolute top-24 left-[8%] w-[240px] sm:w-[380px] h-[240px] sm:h-[380px] bg-[var(--color-brand-blue)]/10 rounded-full blur-[100px] animate-orb-1 pointer-events-none" />
        <div className="absolute top-40 right-[5%] w-[200px] sm:w-[320px] h-[200px] sm:h-[320px] bg-[var(--color-brand-accent)]/15 rounded-full blur-[90px] animate-orb-2 pointer-events-none" />

        <div className="container mx-auto max-w-5xl relative z-10 text-center">
          <motion.div
            initial={false}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7, ease: "easeOut" }}
          >
            <h1 className="font-display text-[40px] xs:text-[48px] sm:text-[64px] md:text-[80px] lg:text-[96px] font-extrabold tracking-[-0.04em] leading-[0.92] text-[var(--color-ink)] mb-4 sm:mb-5">
              Grow<span className="text-[var(--color-brand-blue)]">cin</span>
            </h1>

            <p className="font-display text-[20px] sm:text-[28px] md:text-[34px] font-bold tracking-tight text-[var(--color-ink)] max-w-3xl mx-auto leading-[1.2] mb-3 sm:mb-4 px-1">
              AI Marketing That Actually Grows Your Business
            </p>

            <p
              className="text-[15px] sm:text-base md:text-lg font-medium max-w-2xl mx-auto leading-relaxed mb-6 sm:mb-8 px-1 text-body"
              style={{ color: "#222433", WebkitTextFillColor: "#222433" }}
            >
              Automate SEO, social media, ads, email, and analytics with one AI platform —
              built to turn marketing busywork into measurable growth.
            </p>

            <div className="flex flex-col sm:flex-row items-stretch sm:items-center justify-center gap-3 sm:gap-4 mb-5 sm:mb-6 max-w-md sm:max-w-none mx-auto">
              <Button size="lg" className="w-full sm:w-auto sm:min-w-[180px]" asChild>
                <Link href="/signup">Start Free Trial</Link>
              </Button>
              <Button
                variant="secondary"
                size="lg"
                className="w-full sm:w-auto sm:min-w-[180px] text-slate-900 border-slate-300"
                asChild
              >
                <Link
                  href="#demo"
                  className="inline-flex items-center justify-center gap-2"
                  style={{ color: "#222433", WebkitTextFillColor: "#222433" }}
                >
                  <span className="material-symbols-outlined text-[18px] text-[var(--color-brand-blue)]">
                    play_circle
                  </span>
                  Watch Demo
                </Link>
              </Button>
            </div>

            <p
              className="text-[12px] sm:text-[13px] font-medium px-2 text-body-muted"
              style={{ color: "#475569", WebkitTextFillColor: "#475569" }}
            >
              14-day free trial · No credit card · Setup in under 10 minutes
            </p>
          </motion.div>
        </div>

        {/* Full-bleed product visual */}
        <motion.div
          initial={false}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.9, delay: 0.15, ease: "easeOut" }}
          className="container mx-auto max-w-6xl relative z-10 mt-10 sm:mt-12 md:mt-16"
        >
          <div className="relative mx-auto">
            <div className="absolute -inset-2 sm:-inset-4 md:-inset-8 bg-gradient-to-b from-[var(--color-brand-blue)]/20 via-[var(--color-brand-accent)]/10 to-transparent blur-2xl rounded-[2rem] pointer-events-none" />
            <ProductDashboard activeView={dashView} className="relative" />
          </div>

          <div className="flex flex-wrap items-center justify-center gap-1.5 sm:gap-2 mt-4 sm:mt-5 px-1">
            {(
              [
                ["dashboard", "Dashboard"],
                ["analytics", "Analytics"],
                ["writer", "AI Writer"],
                ["campaigns", "Campaigns"],
              ] as const
            ).map(([key, label]) => (
              <button
                key={key}
                type="button"
                onClick={() => setDashView(key)}
                className={cn(
                  "text-[11px] sm:text-[12px] font-semibold px-3 py-1.5 rounded-full transition-all cursor-pointer",
                  dashView === key
                    ? "bg-[var(--color-brand-blue)] text-white shadow-md shadow-[var(--color-brand-blue)]/25"
                    : "bg-white text-body border border-[var(--color-border-subtle)] hover:border-[var(--color-brand-blue)]/30"
                )}
              >
                {label}
              </button>
            ))}
          </div>
        </motion.div>
      </section>

      {/* Trust strip */}
      <LogoMarquee />

      {/* Stats / social proof */}
      <section className="py-12 sm:py-16 md:py-20 px-4 sm:px-6 bg-[var(--color-base)]">
        <div className="container mx-auto max-w-6xl">
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-6 sm:gap-8 md:gap-6">
            {STATS.map((stat) => (
              <motion.div
                key={stat.label}
                initial={{ opacity: 0, y: 16 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-60px" }}
                transition={{ duration: 0.5 }}
                className="text-center"
              >
                <div className="font-display text-2xl sm:text-3xl md:text-4xl font-extrabold text-[var(--color-ink)] tracking-tight">
                  {stat.value}
                </div>
                <p className="text-xs sm:text-sm text-body mt-2 leading-snug max-w-[160px] sm:max-w-[180px] mx-auto">
                  {stat.label}
                </p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Product showcase */}
      <section id="product" className="py-14 sm:py-20 md:py-28 px-4 sm:px-6 bg-white border-y border-[var(--color-border-subtle)]">
        <div className="container mx-auto max-w-6xl">
          <div className="max-w-2xl mb-10 sm:mb-14 md:mb-16">
            <p className="text-[11px] sm:text-[12px] font-bold uppercase tracking-[0.18em] text-[var(--color-brand-blue)] mb-3">
              The product
            </p>
            <h2 className="font-display text-2xl sm:text-3xl md:text-5xl font-extrabold tracking-tight text-[var(--color-ink)] leading-[1.1] mb-3 sm:mb-4">
              See Growcin — not stock photos
            </h2>
            <p className="text-[15px] sm:text-base md:text-lg text-body leading-relaxed">
              A real workspace for marketers: dashboard, analytics, AI content, and campaign control in one place.
            </p>
          </div>

          <div className="grid sm:grid-cols-2 gap-3 sm:gap-5 md:gap-6">
            {[
              {
                title: "Command center dashboard",
                desc: "Pipeline, ROAS, CPA, and AI-recommended actions — ranked by impact.",
                view: "dashboard" as const,
              },
              {
                title: "Cross-channel analytics",
                desc: "SEO, paid social, and email attributed together so you know what actually drives revenue.",
                view: "analytics" as const,
              },
              {
                title: "AI content generator",
                desc: "Blogs, social posts, ads, and email sequences that match your brand voice.",
                view: "writer" as const,
              },
              {
                title: "Campaign builder & reports",
                desc: "Health status, guardrails, and clear next moves before budget leaks.",
                view: "campaigns" as const,
              },
            ].map((item, i) => (
              <motion.button
                key={item.title}
                type="button"
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-40px" }}
                transition={{ duration: 0.45, delay: i * 0.05 }}
                onClick={() => {
                  setDashView(item.view)
                  document.getElementById("product-preview")?.scrollIntoView({ behavior: "smooth", block: "center" })
                }}
                className="group text-left rounded-2xl border border-[var(--color-border-subtle)] bg-[var(--color-base)] p-5 sm:p-6 md:p-7 hover:border-[var(--color-brand-blue)]/35 hover:shadow-[0_20px_50px_-24px_rgba(144,48,248,0.35)] transition-all cursor-pointer"
              >
                <div className="flex items-start justify-between gap-3 mb-3 sm:mb-4">
                  <h3 className="font-display text-base sm:text-lg md:text-xl font-bold text-[var(--color-ink)]">
                    {item.title}
                  </h3>
                  <span className="material-symbols-outlined text-[var(--color-brand-blue)] opacity-60 group-hover:opacity-100 transition-opacity shrink-0">
                    arrow_outward
                  </span>
                </div>
                <p className="text-sm md:text-[15px] text-body leading-relaxed">
                  {item.desc}
                </p>
              </motion.button>
            ))}
          </div>

          <div id="product-preview" className="mt-8 sm:mt-10 md:mt-12 overflow-hidden">
            <ProductDashboard activeView={dashView} />
          </div>
        </div>
      </section>

      {/* AI Features */}
      <section id="features" className="py-14 sm:py-20 md:py-28 px-4 sm:px-6 bg-[var(--color-base)]">
        <div className="container mx-auto max-w-6xl">
          <div className="text-center max-w-2xl mx-auto mb-10 sm:mb-14">
            <p className="text-[11px] sm:text-[12px] font-bold uppercase tracking-[0.18em] text-[var(--color-brand-blue)] mb-3">
              AI capabilities
            </p>
            <h2 className="font-display text-2xl sm:text-3xl md:text-5xl font-extrabold tracking-tight text-[var(--color-ink)] leading-[1.1] mb-3 sm:mb-4">
              Everything your growth stack needs
            </h2>
            <p className="text-[15px] sm:text-base md:text-lg text-body leading-relaxed">
              From content to campaigns to CRM — Growcin covers the full marketing loop with AI.
            </p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 sm:gap-5">
            {FEATURES.map((f, i) => (
              <motion.div
                key={f.title}
                initial={{ opacity: 0, y: 16 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-40px" }}
                transition={{ duration: 0.4, delay: i * 0.04 }}
                className="group relative rounded-2xl bg-white border border-[var(--color-border-subtle)] p-5 sm:p-6 hover:-translate-y-2 hover:border-[var(--color-brand-blue)]/40 hover:shadow-[0_16px_36px_-12px_rgba(144,48,248,0.18)] transition-all duration-300 flex flex-col justify-between"
              >
                <div>
                  <div className="flex items-center justify-between mb-4">
                    <div className="h-10 w-10 rounded-xl bg-[var(--color-brand-blue)]/10 text-[var(--color-brand-blue)] group-hover:bg-[var(--color-brand-blue)] group-hover:text-white group-hover:scale-110 transition-all duration-300 flex items-center justify-center">
                      <span className="material-symbols-outlined text-[22px]">{f.icon}</span>
                    </div>
                    <span className="text-[10px] font-bold uppercase tracking-wider px-2 py-0.5 rounded-full bg-[var(--color-brand-blue)]/10 text-[var(--color-brand-blue)] group-hover:bg-[var(--color-brand-blue)] group-hover:text-white transition-colors duration-300">
                      {f.badge}
                    </span>
                  </div>
                  <h3 className="font-display font-bold text-[var(--color-ink)] group-hover:text-[var(--color-brand-blue)] transition-colors duration-200 mb-2">
                    {f.title}
                  </h3>
                  <p className="text-sm text-body leading-relaxed mb-4">{f.desc}</p>
                </div>

                <div className="pt-3 border-t border-[var(--color-border-subtle)]/70 flex items-center gap-1.5 text-xs font-semibold text-[var(--color-ink)]">
                  <span className="material-symbols-outlined text-[var(--color-brand-blue)] text-[16px]">
                    check_circle
                  </span>
                  <span>{f.bullet}</span>
                </div>
              </motion.div>
            ))}
          </div>

          <div className="text-center mt-10 sm:mt-12">
            <Button className="w-full sm:w-auto" asChild>
              <Link href="/signup">Try Growcin Free</Link>
            </Button>
          </div>
        </div>
      </section>

      {/* Workflow */}
      <section className="py-14 sm:py-20 md:py-28 px-4 sm:px-6 bg-white border-y border-[var(--color-border-subtle)]">
        <div className="container mx-auto max-w-6xl">
          <div className="text-center max-w-2xl mx-auto mb-10 sm:mb-14">
            <p className="text-[11px] sm:text-[12px] font-bold uppercase tracking-[0.18em] text-[var(--color-brand-blue)] mb-3">
              How it works
            </p>
            <h2 className="font-display text-2xl sm:text-3xl md:text-5xl font-extrabold tracking-tight text-[var(--color-ink)] leading-[1.1] mb-3 sm:mb-4">
              From chaos to a calm growth system
            </h2>
            <p className="text-[15px] sm:text-base md:text-lg text-body leading-relaxed">
              Three steps to replace spreadsheets, tab-hopping, and gut-feel decisions.
            </p>
          </div>

          <div className="grid md:grid-cols-3 gap-8 md:gap-6 relative">
            <div className="hidden md:block absolute top-12 left-[16%] right-[16%] h-px bg-gradient-to-r from-transparent via-[var(--color-brand-blue)]/30 to-transparent" />
            {WORKFLOW.map((step, i) => (
              <motion.div
                key={step.step}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.45, delay: i * 0.1 }}
                className="relative text-center md:text-left"
              >
                <div className="inline-flex h-12 w-12 items-center justify-center rounded-full brand-gradient-bg text-white font-display font-bold text-sm mb-4 sm:mb-5 shadow-lg shadow-[var(--color-brand-blue)]/30">
                  {step.step}
                </div>
                <h3 className="font-display text-lg sm:text-xl font-bold text-[var(--color-ink)] mb-2">
                  {step.title}
                </h3>
                <p className="text-sm sm:text-[15px] text-body leading-relaxed max-w-sm mx-auto md:mx-0">
                  {step.desc}
                </p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Integrations */}
      <section id="integrations" className="py-14 sm:py-20 md:py-28 px-4 sm:px-6 bg-[var(--color-base)]">
        <div className="container mx-auto max-w-6xl">
          <div className="text-center max-w-2xl mx-auto mb-10 sm:mb-12">
            <p className="text-[11px] sm:text-[12px] font-bold uppercase tracking-[0.18em] text-[var(--color-brand-blue)] mb-3">
              Integrations
            </p>
            <h2 className="font-display text-2xl sm:text-3xl md:text-5xl font-extrabold tracking-tight text-[var(--color-ink)] leading-[1.1] mb-3 sm:mb-4">
              Plays nicely with your stack
            </h2>
            <p className="text-[15px] sm:text-base md:text-lg text-body leading-relaxed">
              Connect the tools you already use. Growcin becomes the intelligence layer on top.
            </p>
          </div>

          <div className="grid grid-cols-2 xs:grid-cols-3 sm:grid-cols-4 lg:grid-cols-6 gap-2.5 sm:gap-3 md:gap-4">
            {INTEGRATIONS.map((item) => (
              <div
                key={item.name}
                className="flex flex-col items-center justify-center gap-1.5 sm:gap-2 rounded-xl sm:rounded-2xl bg-white border border-[var(--color-border-subtle)] py-4 sm:py-5 px-2 sm:px-3 hover:border-[var(--color-brand-blue)]/30 transition-colors"
              >
                <span className="material-symbols-outlined text-[var(--color-brand-blue)] text-[22px] sm:text-[26px]">
                  {item.icon}
                </span>
                <span className="text-[10px] sm:text-[11px] md:text-xs font-semibold text-body text-center leading-tight">
                  {item.name}
                </span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Demo */}
      <section id="demo" className="py-14 sm:py-20 md:py-28 px-4 sm:px-6 bg-white border-y border-[var(--color-border-subtle)]">
        <div className="container mx-auto max-w-4xl text-center">
          <p className="text-[11px] sm:text-[12px] font-bold uppercase tracking-[0.18em] text-[var(--color-brand-blue)] mb-3">
            Product demo
          </p>
          <h2 className="font-display text-2xl sm:text-3xl md:text-5xl font-extrabold tracking-tight text-[var(--color-ink)] leading-[1.1] mb-3 sm:mb-4">
            See Growcin in 3 minutes
          </h2>
          <p className="text-[15px] sm:text-base md:text-lg text-body leading-relaxed mb-8 sm:mb-10 max-w-2xl mx-auto">
            Watch how AI drafts content, monitors campaigns, and surfaces the next best action — before budget leaks.
          </p>

          <div className="relative rounded-xl sm:rounded-2xl overflow-hidden border border-[var(--color-border-subtle)] shadow-[0_30px_80px_-40px_rgba(34,36,51,0.45)] aspect-video bg-[var(--color-product)]">
            {demoPlaying ? (
              <iframe
                src="https://www.youtube.com/embed/i2UuGd84ZJU?autoplay=1&rel=0&modestbranding=1"
                title="Growcin product demo"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowFullScreen
                className="absolute inset-0 w-full h-full border-0"
              />
            ) : (
              <button
                type="button"
                onClick={() => setDemoPlaying(true)}
                className="absolute inset-0 w-full h-full flex flex-col items-center justify-center gap-3 sm:gap-4 cursor-pointer group"
              >
                <div className="absolute inset-0 opacity-60"
                  style={{
                    background:
                      "radial-gradient(ellipse at 30% 20%, rgba(144,48,248,0.5), transparent 50%), radial-gradient(ellipse at 80% 80%, rgba(200,48,248,0.3), transparent 45%)",
                  }}
                />
                <div className="relative z-10 h-14 w-14 sm:h-16 sm:w-16 rounded-full bg-white text-[var(--color-brand-blue)] flex items-center justify-center shadow-xl group-hover:scale-110 transition-transform">
                  <span className="material-symbols-outlined text-[32px] sm:text-[36px]" style={{ fontVariationSettings: "'FILL' 1" }}>
                    play_arrow
                  </span>
                </div>
                <p className="relative z-10 text-white font-semibold text-xs sm:text-sm px-4">Play product walkthrough</p>
              </button>
            )}
          </div>

          <div className="flex flex-col sm:flex-row items-stretch sm:items-center justify-center gap-3 mt-8 sm:mt-10 max-w-md sm:max-w-none mx-auto">
            <Button size="lg" className="w-full sm:w-auto" asChild>
              <Link href="/signup">Start Free Trial</Link>
            </Button>
            <Button variant="secondary" size="lg" className="w-full sm:w-auto text-slate-900" asChild>
              <Link href="/signup">Book a Demo</Link>
            </Button>
          </div>
        </div>
      </section>

      {/* Pricing */}
      <section id="pricing" className="py-14 sm:py-20 md:py-28 px-4 sm:px-6 bg-[var(--color-base)]">
        <div className="container mx-auto max-w-6xl">
          <div className="text-center max-w-2xl mx-auto mb-8 sm:mb-10">
            <p className="text-[11px] sm:text-[12px] font-bold uppercase tracking-[0.18em] text-[var(--color-brand-blue)] mb-3">
              Pricing
            </p>
            <h2 className="font-display text-2xl sm:text-3xl md:text-5xl font-extrabold tracking-tight text-[var(--color-ink)] leading-[1.1] mb-3 sm:mb-4">
              Simple plans. Clear value.
            </h2>
            <p className="text-[15px] sm:text-base md:text-lg text-body leading-relaxed mb-6 sm:mb-8">
              Start free. Upgrade when growth is compounding. Monthly or annual — cancel anytime.
            </p>

            <div className="inline-flex items-center gap-2 sm:gap-3 rounded-full bg-white border border-[var(--color-border-subtle)] p-1.5">
              <button
                type="button"
                onClick={() => setIsAnnual(false)}
                className={cn(
                  "h-9 px-3.5 sm:px-4 rounded-full text-sm font-semibold transition-all cursor-pointer",
                  !isAnnual ? "bg-[var(--color-ink)] text-white" : "text-body"
                )}
              >
                Monthly
              </button>
              <button
                type="button"
                onClick={() => setIsAnnual(true)}
                className={cn(
                  "h-9 px-3.5 sm:px-4 rounded-full text-sm font-semibold transition-all cursor-pointer",
                  isAnnual ? "bg-[var(--color-ink)] text-white" : "text-body"
                )}
              >
                Annual <span className="text-[var(--color-status-good)] text-xs ml-1">−20%</span>
              </button>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 sm:gap-5 md:gap-6 items-stretch">
            {[
              {
                name: "Starter",
                price: isAnnual ? 79 : 99,
                blurb: "For founders validating AI-led growth.",
                cta: "Start Free Trial",
                featured: false,
                features: [
                  "AI content studio",
                  "1 ad platform connection",
                  "Basic analytics",
                  "Email support",
                  "14-day free trial",
                ],
              },
              {
                name: "Growth",
                price: isAnnual ? 239 : 299,
                blurb: "For teams scaling multi-channel marketing.",
                cta: "Start Free Trial",
                featured: true,
                features: [
                  "Everything in Starter",
                  "All ad platforms",
                  "CPA guardrails & alerts",
                  "Lead qualification",
                  "Priority support",
                ],
              },
              {
                name: "Agency",
                price: isAnnual ? 799 : 999,
                blurb: "For agencies managing multiple clients.",
                cta: "Contact Sales",
                featured: false,
                features: [
                  "Unlimited workspaces",
                  "White-label reports",
                  "API & custom integrations",
                  "Dedicated success manager",
                  "SLA & onboarding",
                ],
              },
            ].map((plan) => (
              <div
                key={plan.name}
                className={cn(
                  "relative rounded-2xl p-6 sm:p-7 md:p-8 flex flex-col border bg-white",
                  plan.featured
                    ? "border-[var(--color-brand-blue)] shadow-[0_24px_60px_-28px_rgba(144,48,248,0.45)] lg:scale-[1.02] md:col-span-2 lg:col-span-1"
                    : "border-[var(--color-border-subtle)]"
                )}
              >
                {plan.featured && (
                  <div className="absolute -top-3 left-1/2 -translate-x-1/2 brand-gradient-bg text-white text-[10px] font-bold uppercase tracking-widest py-1 px-3 rounded-full whitespace-nowrap">
                    Most popular
                  </div>
                )}
                <h3 className="font-display text-xl font-bold text-[var(--color-ink)]">{plan.name}</h3>
                <p className="text-sm text-body mt-1 mb-5 sm:mb-6">{plan.blurb}</p>
                <div className="mb-5 sm:mb-6">
                  <span className="font-display text-4xl sm:text-5xl font-extrabold text-[var(--color-ink)] tracking-tight">
                    ${plan.price}
                  </span>
                  <span className="text-[var(--color-text-muted)] text-sm">/mo</span>
                </div>
                <Button
                  variant={plan.featured ? "default" : "secondary"}
                  className="w-full mb-6 sm:mb-8"
                  asChild
                >
                  <Link href="/signup">{plan.cta}</Link>
                </Button>
                <ul className="space-y-3 mt-auto">
                  {plan.features.map((f) => (
                    <li key={f} className="flex items-start gap-2.5 text-sm text-body">
                      <span className="material-symbols-outlined text-[var(--color-brand-blue)] text-[18px] shrink-0">
                        check_circle
                      </span>
                      {f}
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>

          <p className="text-center text-sm text-[var(--color-text-muted)] mt-8">
            Need a custom plan?{" "}
            <Link href="/signup" className="text-[var(--color-brand-blue)] font-semibold hover:underline">
              Talk to sales
            </Link>
          </p>
        </div>
      </section>

      {/* Testimonials */}
      <section className="py-14 sm:py-20 md:py-28 px-4 sm:px-6 bg-white border-y border-[var(--color-border-subtle)]">
        <div className="container mx-auto max-w-6xl">
          <div className="text-center max-w-2xl mx-auto mb-10 sm:mb-14">
            <p className="text-[11px] sm:text-[12px] font-bold uppercase tracking-[0.18em] text-[var(--color-brand-blue)] mb-3">
              Testimonials
            </p>
            <h2 className="font-display text-2xl sm:text-3xl md:text-5xl font-extrabold tracking-tight text-[var(--color-ink)] leading-[1.1]">
              Teams that stopped guessing
            </h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 sm:gap-5">
            <TestimonialCard
              quote="Growcin flagged a CPA spike on a real estate campaign within 36 hours. We'd have caught it in the weekly review — four days later. That difference is everything."
              name="Avtar Singh"
              title="CEO, AI Soch Studio"
            />
            <TestimonialCard
              quote="Before Growcin, creative refresh was gut feel and spreadsheets. Now I rotate before CTR falls. Clients see steadier CPA and I spend less time explaining variance."
              name="Abhishek Dhakoliya"
              title="Marketing Head, Best Prop Deal"
            />
            <TestimonialCard
              className="md:col-span-2 lg:col-span-1"
              quote="We finally have one place for content, ads, and lead quality. The AI drafts alone saved our team 15+ hours a week — and the alerts protect the budget."
              name="Priya Mehta"
              title="Founder, Northwave Growth"
            />
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="py-14 sm:py-20 md:py-28 px-4 sm:px-6 bg-[var(--color-base)]">
        <div className="container mx-auto max-w-3xl">
          <div className="text-center mb-8 sm:mb-12">
            <p className="text-[11px] sm:text-[12px] font-bold uppercase tracking-[0.18em] text-[var(--color-brand-blue)] mb-3">
              FAQ
            </p>
            <h2 className="font-display text-2xl sm:text-3xl md:text-4xl font-extrabold tracking-tight text-[var(--color-ink)]">
              Questions, answered
            </h2>
          </div>
          <div className="rounded-2xl bg-white border border-[var(--color-border-subtle)] px-4 sm:px-6 md:px-8">
            <Accordion items={FAQS} />
          </div>
        </div>
      </section>
    </div>
  )
}
